### ISSUE TITLE
i will work on this for this week lol

### ISSUE THREAD

**Issue by Taki21** [BoxOfDevs/BedWars#1]
hi
bye

**Comment by AvgZing** [comment]
You may need to catch up on the new BoxIfDevs team rules

**Comment by AvgZing** [comment]
Before creating a repo, talk with the rest of the team on discord so we can approve/dis-approve it. You may also comment in the issue for it in the Archived repository. This way, we can avoid an overflow on repositories like we used to have

**Comment by AvgZing** [comment]
Also, this looks more like a personal plugin due to the main file path. If it is, please move it out of BoxOfDevs. If you wish to keep the plugin in BoxOfDevs, please change the main file path to /SRC/BoxOfDevs/Bedwars/___.php

**Comment by HimbeersaftLP** [comment]
@TheRoyalBlock Could you please stop, Taki just came back and you already start annoying him...

**Comment by Taki21** [comment]
Oh OK sorry didn't now 
@HimbeersaftLP its OK lol

**Comment by Taki21** [comment]
edited due to internal secrets exposed

**Comment by HimbeersaftLP** [comment]
Funfact: I always wanted to code a BedWars Plugin

**Comment by Taki21** [comment]
@HimbeersaftLP  lol

**Comment by dragonwocky** [comment]
edited due to internal secrets exposed

**Comment by Taki21** [comment]
@TheDragonRing lol ok xD

**Comment by Thunder33345** [comment]
Meh, you could transfer ownership if you think this shouldnt be here

**Comment by AvgZing** [comment]
nah

**Comment by Taki21** [comment]
havent seen @remotevase in months miss da dude xd

**Comment by Vaults1** [comment]
@Taki21 we all do....

**Comment by dragonwocky** [comment]
what did u do @Ultie0???

also what did my message even used to say???

**Comment by AvgZing** [comment]
Your message used to say "me too"
